<?php

// DO NOT EDIT THIS FILE

// PLEASE USING INDEX.PHP FILE IN PUBLIC DIRECTORY

// THE INSTRUCTIONS FOR USING THIS PROJECT IS IN README.MD


require 'vendor/autoload.php';

use Cleaf\Config\Database;

if ($argc !== 2) {
    die("Usage: php migrate.php path/to/sqlfile.sql\n");
}

$sqlFile = $argv[1];

if (!file_exists($sqlFile)) {
    die("File tidak ditemukan: $sqlFile\n");
}

$db = new Database();

try {
    $db->runSQLFile($sqlFile);
    echo "Migrasi berhasil dijalankan!\n";
} catch (Exception $e) {
    echo "Error menjalankan migrasi: " . $e->getMessage() . "\n";
}
